name: Validate Pull Request

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'yarn'
        cache-dependency-path: |
          **/yarn.lock
    - name: Install dependencies
      run: yarn install
    - name: Lint
      run: yarn lint