name: PR Validation

on:
  pull_request:
    branches: [other]

jobs:
  findChanges:
    name: "Find Changes"
    runs-on: ubuntu-latest
    outputs:
      api1: ${{ steps.pathChanges.outputs.api1 }}
      events: ${{ steps.pathChanges.outputs.events }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Resolve path filters
        uses: dorny/paths-filter@v2
        id: pathChanges
        with:
          filters: |
            api1:
              - 'services/api-1/**'
            events:
              - 'services/events/**'
      - name: Output
        run: |
          echo "api1=${{ steps.pathChanges.outputs.api1 }}" >> "$GITHUB_OUTPUT"
          echo "events=${{ steps.pathChanges.outputs.events }}" >> "$GITHUB_OUTPUT"

  validate-api-1:
    name: "Validate API 1"
    needs: findChanges
    if: needs.findChanges.outputs.api1 == 'true'
    uses: danwakeem/github-actions-test/.github/workflows/pr.yml@other
    with:
      stage: dev
      working-directory: services/api-1

  validate-events:
    name: "Validate Events"
    needs: findChanges
    if: needs.findChanges.outputs.events == 'true'
    uses: danwakeem/github-actions-test/.github/workflows/pr.yml@other
    with:
      stage: dev
      working-directory: services/api-1
