name: Events PR

on:
  pull_request:
    branches: [other]
    paths:
      - "services/events/**"
      - ".github/workflows/events.pr.yml"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate
        uses: danwakeem/github-actions-test/.github/workflows/pr.yml@other
        with:
          stage: dev
        working-directory: services/events
