name: Go Console Deploy

on:
  push:
    branches: [main]
    paths:
      - "services/go-console/**"
      - ".github/workflows/go.conosle.yml"
  workflow_dispatch:
    inputs:
      stage:
        description: "Stage to deploy to - IE: dev / prod"
        required: true
        default: "prod"

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    working-directory: ./services/go-console

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      ENV_SITE: ${{ github.event.inputs.stage || 'dev' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: "https://npm.pkg.github.com"
      - name: Deploy
        if: ${{ startsWith(github.event.head_commit.message, 'chore:') }}
        run: |
          echo "$ENV_SITE"
          echo "${{ github.event.head_commit.message }}"
      - uses: google-github-actions/release-please-action@v3
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release-type: simple
          path: services/go-console
          monorepo-tags: true
          package-name: go/console
          tag-separator: '@'
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          prerelease: true
          release-search-depth: 50
          bootstrap-sha: c84af8779c8f03c9d81a68ae3f5d284ada605d67