name: Console UI Deploy

on:
  push:
    tags:
      - 'console-ui*'
    branches: [main]
    paths:
      - "frontends/console-ui/**"
      - ".github/workflows/main.yml"
  workflow_dispatch:
    inputs:
      stage:
        description: "Stage to deploy to - IE: pre / dev / prod"
        required: true
        default: "prod"

defaults:
  run:
    working-directory: ./frontends/console-ui

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      REF_TYPE: ${{ github.ref_name }}
      ENV_SITE: ${{ startsWith(github.ref_name, 'console-ui') && 'dev' || github.event.inputs.stage == 'prod' && 'prod' || 'pre' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: "https://npm.pkg.github.com"
      - name: Test
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$ENV_SITE, $REF_TYPE"
      - run: git fetch --all --tags
      - name: Check Release Version
        uses: thebongy/version-check@v1
        with:
          file: package.json
          tagFormat: console-ui-v${version}
        id: version_check
      - name: tag major and minor versions
        # if: ${{ steps.version_check.versionChanged }}
        env:
          CONTEXT_VAL: ${{ toJson(steps.version_check) }}
        run: |
          echo "$CONTEXT_VAL"