name: Console UI Deploy

on:
  push:
    tags:
      - 'console-ui*'
    branches: [main]
  workflow_dispatch:
    inputs:
      stage:
        description: "Stage to deploy to - IE: pre / dev / prod"
        required: true
        default: "prod"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      ENV_SITE: ${{ startsWith(github.ref_type, 'console-ui') && 'dev' || github.event.inputs.stage == 'prod' && 'prod' || 'pre' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: "https://npm.pkg.github.com"
      - name: Test
        run: |
          echo "$ENV_SITE"
