name: Validate Pull Request

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      stage:
        required: true
        type: string

defaults:
  run:
    working-directory: ${{ github.event.inputs.working-directory }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
